### ISSUE TITLE
What's you python and torch version?

### ISSUE THREAD

**Issue by flymark2010** [bkj/ripenet#3]
Hi, I got error like this: 
```
  File "/workspace/ripenet/workers/cell_worker.py", line 65, in __init__
    self.bn = nn.BatchNorm2d(in_channels, track_running_stats=False)
TypeError: __init__() got an unexpected keyword argument 'track_running_stats'
```
Could you please give more details about the env config? Thanks a lot!

**Comment by bkj** [comment]
```
Python 3.6.4 |Anaconda custom (64-bit)| (default, Jan 16 2018, 18:10:19) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
tor>>> torch.__version__
'0.4.0a0+4c4a42b'
```
Torch installed from master branch of github repo because I wanted to use that `track_running_stats` option.  Turns out that's probably the wrong thing to do -- I just now merge changes that change how batchnorm gets handled.  So you could revert to `torch==0.3` if you don't want to be bothered w/ compilation -- but you'd have to change a couple of small things (both here and in [basenet](https://github.com/bkj/basenet)

**Comment by flymark2010** [comment]
Thanks a lot! I'll try that.

**Comment by flymark2010** [comment]
I can run the project now after modifying one line of code [here](https://github.com/bkj/ripenet/blob/HEAD/workers/cell_worker.py#L124).   

In your code, `/` operator got a `float` type result, but `int` are expected for `torch.zeros`.  And I got an error: 
```
  File "/workspace/ripenet/workers/cell_worker.py", line 124, in forward
    out = Variable(torch.zeros(x.shape[0], self.out_channels, x.shape[2] / self.stride, x.shape[3] / self.stride))
TypeError: torch.zeros received an invalid combination of arguments - got (int, int, float, float), but expected one of:
 * (int ... size)
      didn't match because some of the arguments have invalid types: (int, int, float, float)
 * (torch.Size size)
```

I use Python `3.6.3` and Pytorch `0.3.0.post4`.   

I modified that line to this:
```
out = Variable(torch.zeros(x.shape[0], self.out_channels, x.shape[2] // self.stride, x.shape[3] // self.stride))
```   
so the program can run now. 

Now I'm wondering if I should use `//` or `round` here to cast the `float` value to a `int` one ?

**Comment by bkj** [comment]
Yeah if that's what Pytorch is insisting -- I think `//` or `int(...)` would both work
